
# Allocate sufficient memory for Gradle and the Kotlin daemon
org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8

# When the daemon fails to connect, fallback to in-process compiler instead of failing
kotlin.compiler.execution.strategy=in-process

# Non-transitive R class for faster build performance
android.nonTransitiveRClass=true
# Enable AndroidX support libraries
android.useAndroidX=true

# Automatically convert third-party libraries to use AndroidX
android.enableJetifier=true

# JVM allocation for Gradle Daemon

kotlin.code.style=official